/** See the file "LICENSE" for the full license governing this code. */

package au.org.ands.vocabs.registry.api.auth;

/** Constants used in authorization and authentication. */
public final class AuthConstants {

    /** Private constructor for utility class. */
    private AuthConstants() {
    }

    /* Constants related to data stored in the Roles database. */

    /** Functional role added by CodeIgniter for all users.
     * For consistency, we add it as a permission for all successful logins. */
    public static final String AUTH_FUNCTION_DEFAULT_ATTRIBUTE =
            "PUBLIC";

    /** Functional role added by CodeIgniter for logged-in users.
     * For consistency, we add it as a permission for all successful logins. */
    public static final String AUTH_FUNCTION_LOGGED_IN_ATTRIBUTE =
            "AUTHENTICATED_USER";

    /* Constants related to how we represent authentication/authorization
     * data. */

    /** Attribute used in Profiles to store complete UserInfo data. */
    public static final String USER_INFO = "rolesUserInfo";

    /** Name of the pac4j direct Client that "authenticates" as an
     * anonymous user. */
    public static final String ANON_CLIENT = "anon";

    /** Name of the pac4j direct Client that authenticates using
     * a provided username and password. */
    public static final String USERPASS_CLIENT = "userpass";

    /** Name of the pac4j direct Client that authenticates using
     * a header that contains a cookie generated by the
     * RDA-flavoured CodeIgniter library. */
    public static final String RDA_HEADER_CLIENT = "rdaHeader";

    /** Name of the pac4j direct Client that authenticates using
     * a provided cookie generated by the RDA-flavoured CodeIgniter
     * library. */
    public static final String RDA_COOKIE_CLIENT = "rdaCookie";

    /** List of clients that require authorization credentials.
     * Use this as the value of the clients parameter of the
     * Pac4JSecurity annotation, to require that the user log in
     * to be able to access this method. */
    public static final String MUST_HAVE_CREDENTIALS =
            USERPASS_CLIENT + "," + RDA_HEADER_CLIENT + RDA_COOKIE_CLIENT;

    /** List of clients that require authorization credentials,
     * or that allow "anonymous" access.
     * Use this as the value of the clients parameter of the
     * Pac4JSecurity annotation, to allow access to the method
     * with or without logging in. */
    public static final String MAY_HAVE_CREDENTIALS =
            USERPASS_CLIENT + "," + RDA_HEADER_CLIENT
            + "," + RDA_COOKIE_CLIENT + "," + ANON_CLIENT;


//    /** . */
//    public static final String  = "";
//

}
