/** See the file "LICENSE" for the full license governing this code. */
/** Registry Database schema; these classes are generated from an
 * XML Schema definition.
 * Classes in this package are generated by xjc;
 * do not edit them! */
package au.org.ands.vocabs.registry.db.internal;
