/** See the file "LICENSE" for the full license governing this code. */
/** Registry schema; these classes are generated from the
 * registry schema definition.
 * Classes in this package are generated by xjc;
 * do not edit them! */
package au.org.ands.vocabs.registry.schema.vocabulary201701;
